name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies for native crates
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libglib2.0-dev \
          libgtk-3-dev \
          libgdk-pixbuf2.0-dev \
          libjavascriptcoregtk-4.1-dev \
          libwebkit2gtk-4.1-dev \
          libpango1.0-dev \
          libatk1.0-dev \
          pkg-config \
          build-essential

    - name: Build
      run: cargo build --release

    - name: Run tests
      run: cargo test --release
