on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies for glib-sys and gdk-sys
      run: |
        sudo apt-get update
        sudo apt-get install -y libglib2.0-dev libgtk-3-dev libgdk-pixbuf2.0-dev pkg-config

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
